name:                do-remember
version:             0.1.0.0
github:              "michaelmmacleod/do-remember"
license:             BSD3
author:              "Michael MacLeod"
maintainer:          "michaelmmacleod@gmail.com"
copyright:           "BSD3"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/michaelmmacleod/do-remember#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  do-remember-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - do-remember

tests:
  do-remember-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - do-remember
